
services:
  kong-database:
    image: postgres:12
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8444 ssl
      KONG_SSL_CERT: /etc/kong/ssl/cert.pem
      KONG_SSL_CERT_KEY: /etc/kong/ssl/key.pem
    volumes:
      - ./ssl/cert.pem:/etc/kong/ssl/cert.pem
      - ./ssl/key.pem:/etc/kong/ssl/key.pem
    ports:
      - "8443:8443"
      - "8444:8444"
    depends_on:
      - kong-database
    networks:
      - kong-net

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
